name: Self Hosted Runner Test

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Command
        run: echo "Self-hosted runner working"
